### ISSUE TITLE
Can we simply run for specific chromosome?

### ISSUE THREAD

**Issue by mullinyu** [BilkentCompGen/hercules#6]
Hi,

I have a specific question to find phasing of tow mutations on chr21. I would like to know can I simply do some filtering in advance to get those reads of chr21 from short&long reads and then use Hercules to correct reads of chr21 only. This has the assumption that the bam files of short and long reads are mapping correctly in advance.

Many thanks!

**Comment by canfirtina** [comment]
Hi @mullinyu ,

I will describe the method that I would suggest in several steps:

1. Align separately both short and long reads to the chr21. Let's say the alignment of the short reads to the chr21 is stored in short.bam, and similarly the alignment of the long reads to the chr21 is in long.bam.
2. Collect & sort the read names that appear in short.bam and long.bam in a text file such as short_reads.txt and long_reads.txt, respectively. Make sure that each line contains a single read id and the read ids are unique inside those files i.e., the same read id does not appear more than once inside the same file.
3. You can use the tool called seqtk to fetch the specific reads from a fasta/fastq file given the list of the read ids, which you will already have in short_reads.txt and long_reads.txt. This will create a fasta/fastq file that contains the reads that appear in short_reads.txt and long_reads.txt.
4. Then, you can simply use these fasta/fastq files with Hercules.

Some remarks: As you said these steps assume that the mapped reads are actually correct. However, note that you will automatically lose the unmapped long reads that would have mapped to the chr21 after the correction due to the fact that there may be some reads that cannot map because of the high error rate that they contain. After the correction, it may be possible for some of those reads to map to the reference. However, since you will correct only the reads that map to the chr21, you will lose such reads.

I hope that helps and thank you for your interest using Hercules.

Best,

Can

**Comment by mullinyu** [comment]
Many thanks for your detailed explanation. I'll try!!
